add prefix FFRT_ to REG names
REG_SP has been defined in third_party/musl/usr/include/riscv64-linux-ohos/bits/signal.h
change the name to FFRT_REG_SP to avoid ambiguity.

 ../../foundation/resourceschedule/ffrt/src/eu/co2_context.h:41:9: error: 'REG_SP' macro redefined [-Werror,-Wmacro-redefined]
 #define REG_SP 0
         ^
 obj/third_party/musl/usr/include/riscv64-linux-ohos/bits/signal.h:41:9: note: previous definition is here
 #define REG_SP 2
         ^
 1 error generated.

Signed-off-by: Polyos Project (陈荣) <polyos@iscas.ac.cn>